'001':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-01_220530/config.yml
  scene_name: '001'
'002':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-car-depth-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-car-depth-recon/2024-02-13_152802/config.yml
  scene_name: '002'
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-car-depth-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-car-depth-recon/2024-02-16_131741/config.yml
  scene_name: '002'
'003':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-07_205604/config.yml
  scene_name: '003'
'005':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-08_203245/config.yml
  scene_name: '005'
008:
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-02-04_120123/config.yml
  scene_name: 008
'011':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-car-depth-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-car-depth-recon/2024-02-08_102959/config.yml
  scene_name: '011'
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-02-26_170958/config.yml
  scene_name: '011'
'012':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-car-depth-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-car-depth-recon/2024-02-21_081220/config.yml
  scene_name: '012'
'013':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-09_093447/config.yml
  scene_name: '013'
'015':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-09_201220/config.yml
  scene_name: '015'
'021':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-11_220043/config.yml
  scene_name: '021'
'023':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-19_191959/config.yml
  scene_name: '023'
'027':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-21_164506/config.yml
  scene_name: '027'
'033':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-29_215034/config.yml
  scene_name: '033'
'035':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-30_221631/config.yml
  scene_name: '035'
'037':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-31_124043/config.yml
  scene_name: '037'
039:
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-04-02_191130/config.yml
  scene_name: 039
'103':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-04-02_184647/config.yml
  scene_name: '103'
'105':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-30_221653/config.yml
  scene_name: '105'
'109':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-29_215102/config.yml
  scene_name: '109'
'113':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-27_194903/config.yml
  scene_name: '113'
'117':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-19_192547/config.yml
  scene_name: '117'
'119':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-11_211357/config.yml
  scene_name: '119'
'139':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-09_201326/config.yml
  scene_name: '139'
'149':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: night
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-08_203810/config.yml
  scene_name: '149'
