'001':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-03-01_220530/config.yml
  scene_name: '001'
'002':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-car-depth-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-car-depth-recon/2024-02-13_152802/config.yml
  scene_name: '002'
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-car-depth-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-car-depth-recon/2024-02-16_131741/config.yml
  scene_name: '002'
008:
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-02-04_120123/config.yml
  scene_name: 008
'011':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-car-depth-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-car-depth-recon/2024-02-08_102959/config.yml
  scene_name: '011'
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-nerfacto-object-wise-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-nerfacto-object-wise-recon/2024-02-26_170958/config.yml
  scene_name: '011'
'012':
- !SceneConfig
  cameras:
  - front_camera
  light_condition: day
  method_name: mars-pandaset-car-depth-recon
  road_type: Not yet implemented.
  scene_config_path: /zfs/penshorn/master_thesis/code/mars-synthetic-data/outputs/PandaSet/mars-pandaset-car-depth-recon/2024-02-21_081220/config.yml
  scene_name: '012'
