!SyntheticDataPipelineConfig
camera_jitter: 0.0
generate_synthetic_trajectories: true
light_conditions:
- day
max_acceleration_check: 5
max_object_distance: 25
max_velocity_check: 50
n_closest_objects: 5
n_frames_min_objects: 15
n_scenes: 73
name: pandaset_day_synthetic_trajectories_50_percent_other_scenes
original_dataset_root: !!python/object/apply:pathlib.PosixPath
- /
- zfs
- penshorn
- master_thesis
- datasets
- raw
- PandaSet
percentage_models_other_scene: 0.5
print_spline_loss: false
return_spline_optimizer: false
scene_configs_path: !!python/object/apply:pathlib.PosixPath
- /
- zfs
- penshorn
- master_thesis
- code
- mars-synthetic-data
- synthetic_data_generation
- scene_configs_decent_miraculix.yaml
seed: 3397265086
select_object_model_weights:
- 80
- 15
- 5
spline_add_noise_to_observations: false
spline_grid_class: catmull_rom
spline_max_control_points: 10
spline_max_noise: 0.2
spline_optimization_steps: 5000
swap_object_models_within_scene: false
synthetic_dataset_root: !!python/object/apply:pathlib.PosixPath
- /
- zfs
- penshorn
- master_thesis
- datasets
- synthetic
- PandaSet_day_synthetic_trajectories_50_percent_other_scenes
trajectory_sampling_jitter: 0.25
